version: '3.1'

services:
  db:
    image: mariadb:10.7.1
    environment:
        MYSQL_ROOT_PASSWORD: vibinsystem
        MYSQL_DATABASE: vibinapp
        MYSQL_USER: vibinsystem
        MYSQL_PASSWORD: vibinsystem
    ports:
        - 3306:3306

  minio:
    image: quay.io/minio/minio:latest
    command: 'server /data --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin_password