version: '3.1'

services:
  db:
    image: mariadb:10.7.1
    environment:
        MYSQL_ROOT_PASSWORD: vibinsystem
        MYSQL_DATABASE: vibinapp
        MYSQL_USER: vibinsystem
        MYSQL_PASSWORD: vibinsystem
    ports:
        - 3306:3306