---
spring:
  main:
    banner-mode: off

keycloak:
  # Client manages Token for now
  bearer-only: true
  # TODO: Figure out if needed
  use-resource-role-mappings: "true"
  # Attribute needs to be the unique DB uuid => allows UUID.fromString(principal.getName())
  principal-attribute: id


#  use-resource-role-mappings: true
