---
server:
  port: 8891

  #spring:
  #  datasource:
  #    username: vibinsystem
  #    password: vibinsystem
  #    url: jdbc:mariadb://localhost:3306/vibinapp

keycloak:
  realm: master
  auth-server-url: http://localhost:8888/auth
  ssl-required: none
  # ssl-required: external
  resource: test-client
  public-client: true
  confidential-port: 0

spring:
  mvc:
    async:
      # Amount of time before asynchronous request handling times out.
      request-timeout: 10000

vibin:
  disabled: false
  account: "AC7eb55afa42f9ccb4ca0c3f1b81d024c2"
  key: "SK0055386c2f9acc72c7eccb1138641f1c"

  # Configures the Keycloak User managed by this server
  backend:
    hasura:
      host: 'http://localhost:8090/v1/graphql'
    user:
      name: example-user
      password: example-password
