---
server:
  port: 8891

  #spring:
  #  datasource:
  #    username: vibinsystem
  #    password: vibinsystem
  #    url: jdbc:mariadb://localhost:3306/vibinapp

keycloak:
  realm: master
  auth-server-url: http://localhost:8888/auth
  ssl-required: none
  # ssl-required: external
  resource: test-client
  public-client: true
  confidential-port: 0

spring:
  mvc:
    async:
      # 5 Minutes inactivity kills an async request
      request-timeout: 10000

vibin:
  enabled: true
  token: "twilio-example-token"
  account: "twilio-example-account"
  key: "twilio-example-key"

  # Configures the Keycloak User managed by this server
  backend:
    hasura:
      host: 'http://localhost:8090/v1/graphql'
    user:
      name: example-user
      password: example-password
